# Generated by Django 4.0.5 on 2022-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blood_bank_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
