# Generated by Django 4.0.5 on 2022-06-14 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blood_bank_city_alter_blood_bank_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_bank',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blood_bank',
            name='pincode',
        ),
    ]
